export const SET_COUNTRY = 'SET_COUNTRY';
export const SET_TOTAL_INDO = 'SET_TOTAL_INDO';
export const SET_TOTAL_DUNI = 'SET_TOTAL_DUNI';
export const SET_DETAIL_CASE_INDO = 'SET_DETAIL_CASE_INDO';
export const SET_DETAIL_CASE_DUNI = 'SET_DETAIL_CASE_DUNI';
